; Os textos do instalador em portugues e em ingles (incluido pelo karaoke.nsi, depois dos MUI_LANGUAGE).
; Em cada par: primeiro o portugues, depois o ingles.

LangString T_NOME ${LANG_PORTUGUESEBR} "IOkê"
LangString T_NOME ${LANG_ENGLISH} "IOkê"

LangString T_CANCELAR ${LANG_PORTUGUESEBR} "Cancelar a instalação do IOkê?"
LangString T_CANCELAR ${LANG_ENGLISH} "Cancel the IOkê installation?"

LangString T_BOAS_VINDAS ${LANG_PORTUGUESEBR} "Este assistente instala o IOkê neste computador.$\r$\n$\r$\nNa primeira vez ele baixa da internet o Python, a separação de voz (PyTorch, uns 3 a 4 GB com placa NVIDIA; sem ela, dá para escolher a instalação leve, que separa na nuvem) e os modelos. Pode levar um bom tempo: deixe o computador ligado e conectado.$\r$\n$\r$\nSuas músicas, contas e configurações nunca são apagadas: nem ao instalar, nem ao atualizar, nem ao desinstalar."
LangString T_BOAS_VINDAS ${LANG_ENGLISH} "This wizard installs IOkê on this computer.$\r$\n$\r$\nThe first time, it downloads Python, the voice separation (PyTorch, about 3 to 4 GB with an NVIDIA card; without one, you can choose the light install, which separates in the cloud) and the models. It can take a while: keep the computer on and connected.$\r$\n$\r$\nYour songs, accounts and settings are never deleted: not when installing, updating or uninstalling."

LangString T_PROG_TITULO ${LANG_PORTUGUESEBR} "Pasta do programa"
LangString T_PROG_TITULO ${LANG_ENGLISH} "Program folder"
LangString T_PROG_SUB ${LANG_PORTUGUESEBR} "Onde o IOkê fica instalado."
LangString T_PROG_SUB ${LANG_ENGLISH} "Where IOkê is installed."
LangString T_PROG_TEXTO ${LANG_PORTUGUESEBR} "O programa (e as versões que você baixar pelo app) fica nesta pasta. Seus dados ficam em outra, na próxima tela."
LangString T_PROG_TEXTO ${LANG_ENGLISH} "The program (and the versions you download from the app) goes in this folder. Your data goes in another one, on the next screen."

LangString T_DADOS_TITULO ${LANG_PORTUGUESEBR} "Pasta dos seus dados"
LangString T_DADOS_TITULO ${LANG_ENGLISH} "Your data folder"
LangString T_DADOS_SUB ${LANG_PORTUGUESEBR} "Músicas, contas, modelos e configurações."
LangString T_DADOS_SUB ${LANG_ENGLISH} "Songs, accounts, models and settings."
LangString T_DADOS_TEXTO ${LANG_PORTUGUESEBR} "Se você já usa o IOkê, escolha a pasta onde estão as pastas data e models e o config.json (a pasta antiga do projeto): tudo é usado como está, nada é movido nem apagado.$\r$\n$\r$\nSe é a primeira vez, deixe a sugestão (ou escolha um disco com bastante espaço: as músicas ocupam alguns GB)."
LangString T_DADOS_TEXTO ${LANG_ENGLISH} "If you already use IOkê, choose the folder with the data and models folders and config.json (the old project folder): everything is used as it is, nothing is moved or deleted.$\r$\n$\r$\nIf this is the first time, keep the suggestion (or choose a disk with plenty of space: songs take a few GB)."
LangString T_DADOS_PASTA ${LANG_PORTUGUESEBR} "Pasta de dados"
LangString T_DADOS_PASTA ${LANG_ENGLISH} "Data folder"

LangString T_FIM_TITULO ${LANG_PORTUGUESEBR} "IOkê instalado"
LangString T_FIM_TITULO ${LANG_ENGLISH} "IOkê installed"
LangString T_FIM_TEXTO ${LANG_PORTUGUESEBR} "Pronto! O IOkê abre em tela cheia (F11 alterna para janela). Para sair, use o botão de desligar no canto de cima ou Alt+F4.$\r$\n$\r$\nAtualizações: Configurações → Atualizações → Procurar atualizações."
LangString T_FIM_TEXTO ${LANG_ENGLISH} "Done! IOkê opens in full screen (F11 switches to a window). To quit, use the power button in the top corner or Alt+F4.$\r$\n$\r$\nUpdates: Settings → Updates → Check for updates."
LangString T_ABRIR_AGORA ${LANG_PORTUGUESEBR} "Abrir o IOkê agora"
LangString T_ABRIR_AGORA ${LANG_ENGLISH} "Open IOkê now"

LangString T_PASTA_DATA ${LANG_PORTUGUESEBR} "Você escolheu a pasta data. Vou usar a pasta de cima, que é onde ficam data, models e config.json:"
LangString T_PASTA_DATA ${LANG_ENGLISH} "You chose the data folder. I'll use the folder above it, where data, models and config.json are:"
LangString T_DADOS_FORA ${LANG_PORTUGUESEBR} "A pasta de dados precisa ficar fora da pasta do programa ($INSTDIR). Escolha outra."
LangString T_DADOS_FORA ${LANG_ENGLISH} "The data folder must be outside the program folder ($INSTDIR). Choose another one."
LangString T_ACHEI_MUSICAS ${LANG_PORTUGUESEBR} "Encontrei suas músicas nesta pasta. O IOkê vai usar tudo como está (nada é movido nem apagado)."
LangString T_ACHEI_MUSICAS ${LANG_ENGLISH} "I found your songs in this folder. IOkê will use everything as it is (nothing is moved or deleted)."

LangString T_PERFIL_TITULO ${LANG_PORTUGUESEBR} "Como separar as músicas"
LangString T_PERFIL_TITULO ${LANG_ENGLISH} "How to separate the songs"
LangString T_PERFIL_SUB ${LANG_PORTUGUESEBR} "Não encontrei placa de vídeo NVIDIA neste computador."
LangString T_PERFIL_SUB ${LANG_ENGLISH} "I didn't find an NVIDIA graphics card on this computer."
LangString T_PERFIL_TEXTO ${LANG_PORTUGUESEBR} "A separação da voz precisa de uma placa NVIDIA para ser rápida. Sem ela, escolha:"
LangString T_PERFIL_TEXTO ${LANG_ENGLISH} "Voice separation needs an NVIDIA card to be fast. Without one, choose:"
LangString T_PERFIL_LEVE ${LANG_PORTUGUESEBR} "Leve (recomendada): separa as músicas na nuvem, na sua conta Modal. Uns 400 MB."
LangString T_PERFIL_LEVE ${LANG_ENGLISH} "Light (recommended): separates the songs in the cloud, on your Modal account. About 400 MB."
LangString T_PERFIL_LEVE_TEXTO ${LANG_PORTUGUESEBR} "Cada música custa alguns centavos de dólar (o Modal dá US$$ 30 grátis por mês). Você conecta a conta depois, em Configurações → Nuvem."
LangString T_PERFIL_LEVE_TEXTO ${LANG_ENGLISH} "Each song costs a few cents (Modal gives US$$ 30 free per month). You connect the account later, in Settings → Cloud."
LangString T_PERFIL_CPU ${LANG_PORTUGUESEBR} "Completa, no processador: separa neste PC, bem devagar (10–20 min por música). Uns 2 GB."
LangString T_PERFIL_CPU ${LANG_ENGLISH} "Full, on the processor: separates on this PC, very slowly (10–20 min per song). About 2 GB."
LangString T_PERFIL_DEPOIS ${LANG_PORTUGUESEBR} "Dá para trocar depois em Configurações → Programa → Instalação."
LangString T_PERFIL_DEPOIS ${LANG_ENGLISH} "You can change this later in Settings → Program → Installation."

LangString T_BAIXANDO_PYTHON ${LANG_PORTUGUESEBR} "Baixando o Python do IOkê..."
LangString T_BAIXANDO_PYTHON ${LANG_ENGLISH} "Downloading IOkê's Python..."
LangString T_PYTHON_FALHOU ${LANG_PORTUGUESEBR} "Não consegui baixar o Python (código $0). Confira a internet e rode o instalador de novo."
LangString T_PYTHON_FALHOU ${LANG_ENGLISH} "Couldn't download Python (code $0). Check the internet and run the installer again."
LangString T_PREPARANDO ${LANG_PORTUGUESEBR} "Preparando o IOkê ${VERSION}. Na primeira vez baixa de 400 MB (leve) a 4 GB (placa NVIDIA): pode levar bastante tempo..."
LangString T_PREPARANDO ${LANG_ENGLISH} "Preparing IOkê ${VERSION}. The first time it downloads 400 MB (light) to 4 GB (NVIDIA card): it can take a while..."
LangString T_INSTALACAO_FALHOU ${LANG_PORTUGUESEBR} "A instalação não terminou (código $0). O que aconteceu está em:$\r$\n$INSTDIR\logs\instalacao.log$\r$\n$\r$\nRodar o instalador de novo continua de onde parou."
LangString T_INSTALACAO_FALHOU ${LANG_ENGLISH} "The installation didn't finish (code $0). What happened is in:$\r$\n$INSTDIR\logs\instalacao.log$\r$\n$\r$\nRunning the installer again continues where it stopped."
LangString T_FIREWALL ${LANG_PORTUGUESEBR} "Liberando os celulares no firewall (o Windows pede permissão uma vez)..."
LangString T_FIREWALL ${LANG_ENGLISH} "Allowing phones through the firewall (Windows asks for permission once)..."
LangString T_REMOVIDO ${LANG_PORTUGUESEBR} "O IOkê foi removido. Suas músicas, contas e configurações continuam em:"
LangString T_REMOVIDO ${LANG_ENGLISH} "IOkê was removed. Your songs, accounts and settings are still in:"
